### ISSUE TITLE
NPE when running bundleMon

### ISSUE THREAD

**Issue by ioleo** [armanbilge/sbt-bundlemon#64]
When I enable the plugin and run `bundleMon` on the project I'm getting

> java.lang.NullPointerException: Cannot invoke "String.split(String)" because the return value of "scala.collection.SeqLike.toString()" is null

Scala `v3.3.1`
ScalaJS `v1.14.0`
BundleMon `v.0.1.3`

**Comment by armanbilge** [comment]
> When I enable the plugin and run `bundleMon` on the project I'm getting

Are you attempting to run it locally? The plugin is designed and intended only to run in GitHub Actions CI.

**Comment by ioleo** [comment]
Yeah, I attempted to run it locally

**Comment by armanbilge** [comment]
We should improve the error message anyway, let's leave it open :)
